### ISSUE TITLE
Parker markers not working on all citys

### ISSUE THREAD

**Issue by codexGW** [A3Armory/A3A_A3Wasteland.Stratis#1]
I placed 3 parking markers and 3 spawn markers on Stratis next to placed parking structures and the only one that worked was Kamino Firing Range. The Air Base and Camp Maxwell didn't work. I have a doctors appointment this morning but will try and fix it later today.

**Comment by AgentRev** [comment]
You must remove all your old parking and storage stuff from Stratis, and implement those from the [VanillaLayer](https://github.com/A3Wasteland/ArmA3_Wasteland.Stratis/blob/megamerge/mission.sqm#L8930-L9156). They are not intercompatible. The final result is identical to the sock mission.

Use this as needed: https://gist.github.com/AgentRev/c0ff379c54a9c7ab6c8d

**Comment by codexGW** [comment]
The storage works fine but I will added it to the VanillaLayer. Is this what your talking about for the parking? I think I did it right.
https://github.com/A3Armory/A3A_A3Wasteland.Stratis/commit/558df4031d63f91dbfb77fb51655bc19da542b93#diff-f2265d99ce277e6133bff859ea54974eR10775

**Comment by codexGW** [comment]
Oh I get it, the buildings need to be in there too. Thanks man... duh

**Comment by AgentRev** [comment]
You need to delete all your old parking sheds and storage boxes, and use the ones from the VanillaLayer.

**Comment by codexGW** [comment]
Cool, I will.

**Comment by codexGW** [comment]
https://github.com/A3Armory/A3A_A3Wasteland.Stratis/commit/1e25a6ca192571565e63dba03e4c917267de058c#diff-f2265d99ce277e6133bff859ea54974eR10610

**Comment by ghost** [comment]
Yes rev i pulled ? your latest Stratis version https://github.com/ccgmatt76/ArmA3_Wasteland.Stratis/commits/megamerge

i'll open the editor up in a mo and see if there are a few duplicate markers

**Comment by ghost** [comment]
nope no duplicates, Thanks Gig but this is vanilla Stratis i'm running at the mo, it should work ?
